title: Bambooom
author: bambooom
email: zhuzi.mn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Blog of Bambooom

baseurl: ""
url: "https://zhuzi.dev"
permalink: /:year/:month/:day/:title/
lang: zh-Hans # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
google_analytics: G-JZXBDG8XEP

github_username: bambooom
twitter_username: bo0omzi
instagram_username: milkymono
telegram_username: bambooom
disqus_shortname: bamboooom
# Build settings
markdown: kramdown
# theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock
